# Generated by Django 5.2.17 on 2026-08-18 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0002_initial'),
        ('tickets', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_definitions_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_definitions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('conversation', 'Conversation'), ('ticket', 'Ticket'), ('api', 'API')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('budget_exceeded', 'Budget exceeded')], default='pending', max_length=20)),
                ('input_message', models.TextField()),
                ('input_metadata', models.JSONField(blank=True, default=dict)),
                ('final_response', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message_safe', models.CharField(blank=True, max_length=255)),
                ('model_call_count', models.PositiveIntegerField(default=0)),
                ('step_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='conversations.conversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs_created', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='tickets.ticket')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('run_started', 'Run started'), ('request_normalized', 'Request normalized'), ('budget_checked', 'Budget checked'), ('provider_call_started', 'Provider call started'), ('provider_call_succeeded', 'Provider call succeeded'), ('provider_call_failed', 'Provider call failed'), ('response_finalized', 'Response finalized'), ('run_completed', 'Run completed'), ('run_failed', 'Run failed'), ('run_cancelled', 'Run cancelled')], max_length=32)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='succeeded', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('input_summary', models.CharField(blank=True, max_length=500)),
                ('output_summary', models.CharField(blank=True, max_length=500)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.agentrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_steps', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['run_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('system_prompt', models.TextField(blank=True)),
                ('provider', models.CharField(choices=[('fake', 'Deterministic fake'), ('openai', 'OpenAI')], max_length=32)),
                ('model', models.CharField(max_length=128)),
                ('temperature', models.FloatField(default=0.0)),
                ('max_output_tokens', models.PositiveIntegerField(default=512)),
                ('max_model_calls', models.PositiveIntegerField(default=1)),
                ('max_steps', models.PositiveIntegerField(default=20)),
                ('wall_time_limit_seconds', models.PositiveIntegerField(default=30)),
                ('provider_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('max_estimated_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_retry_attempts', models.PositiveIntegerField(default=1)),
                ('runtime_config', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('agent_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agents.agentdefinition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='agent_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='agents.agentversion'),
        ),
        migrations.AddIndex(
            model_name='agentdefinition',
            index=models.Index(fields=['workspace', 'status'], name='agent_def_workspace_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdefinition',
            index=models.Index(fields=['workspace', '-created_at'], name='agent_def_ws_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='agent_def_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='agent_def_workspace_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['workspace', 'run'], name='agent_step_workspace_run_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentstep',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='agent_step_run_sequence_uniq'),
        ),
        migrations.AddIndex(
            model_name='agentversion',
            index=models.Index(fields=['agent_definition', 'status'], name='agent_ver_def_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentversion',
            constraint=models.UniqueConstraint(fields=('agent_definition', 'version'), name='agent_ver_definition_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='agentversion',
            constraint=models.CheckConstraint(condition=models.Q(('max_model_calls__gte', 1)), name='agent_ver_max_calls_gte_1'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['workspace', 'status'], name='agent_run_workspace_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['workspace', '-created_at'], name='agent_run_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent_version'], name='agent_run_agent_version_idx'),
        ),
    ]
