# Generated by Django 5.2.17 on 2026-08-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="tool_call_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentversion",
            name="max_tool_calls",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="agentstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("run_started", "Run started"),
                    ("request_normalized", "Request normalized"),
                    ("budget_checked", "Budget checked"),
                    ("provider_call_started", "Provider call started"),
                    ("provider_call_succeeded", "Provider call succeeded"),
                    ("provider_call_failed", "Provider call failed"),
                    ("response_finalized", "Response finalized"),
                    ("run_completed", "Run completed"),
                    ("run_failed", "Run failed"),
                    ("run_cancelled", "Run cancelled"),
                    ("tool_requested", "Tool requested"),
                    ("tool_validation_failed", "Tool validation failed"),
                    ("tool_execution_started", "Tool execution started"),
                    ("tool_execution_succeeded", "Tool execution succeeded"),
                    ("tool_execution_failed", "Tool execution failed"),
                    ("tool_execution_timed_out", "Tool execution timed out"),
                    ("tool_idempotency_reused", "Tool idempotency reused"),
                ],
                max_length=32,
            ),
        ),
    ]
