# Generated by Django 5.2.17 on 2026-08-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agentrun_status_alter_agentstep_step_type'),
        ('conversations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='output_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run_output', to='conversations.message'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='trigger_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run', to='conversations.message'),
        ),
    ]
