# Generated by Django 5.2.17 on 2026-08-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_agentrun_output_message_agentrun_trigger_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("budget_exceeded", "Budget exceeded"),
                    ("waiting_for_approval", "Waiting for approval"),
                    ("handed_off", "Handed off to a human"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agentstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("run_started", "Run started"),
                    ("request_normalized", "Request normalized"),
                    ("budget_checked", "Budget checked"),
                    ("provider_call_started", "Provider call started"),
                    ("provider_call_succeeded", "Provider call succeeded"),
                    ("provider_call_failed", "Provider call failed"),
                    ("response_finalized", "Response finalized"),
                    ("run_completed", "Run completed"),
                    ("run_failed", "Run failed"),
                    ("run_cancelled", "Run cancelled"),
                    ("tool_requested", "Tool requested"),
                    ("tool_validation_failed", "Tool validation failed"),
                    ("tool_execution_started", "Tool execution started"),
                    ("tool_execution_succeeded", "Tool execution succeeded"),
                    ("tool_execution_failed", "Tool execution failed"),
                    ("tool_execution_timed_out", "Tool execution timed out"),
                    ("tool_idempotency_reused", "Tool idempotency reused"),
                    ("risk_assessed", "Risk assessed"),
                    ("policy_evaluated", "Policy evaluated"),
                    ("approval_requested", "Approval requested"),
                    ("approval_approved", "Approval approved"),
                    ("approval_rejected", "Approval rejected"),
                    ("approval_expired", "Approval expired"),
                    ("run_waiting_for_approval", "Run waiting for approval"),
                    ("execution_resumed", "Execution resumed"),
                    ("handoff_requested", "Handoff requested"),
                    ("run_handed_off", "Run handed off"),
                ],
                max_length=32,
            ),
        ),
    ]
