# Generated by Django 5.2.17 on 2026-08-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agentrun_status_alter_agentstep_step_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('conversation', 'Conversation'), ('ticket', 'Ticket'), ('api', 'API'), ('evaluation', 'Evaluation')], default='manual', max_length=20),
        ),
    ]
