# Generated by Django 5.2.17 on 2026-09-04 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_agentrun_trigger'),
        ('conversations', '0003_alter_message_options_message_sequence'),
        ('tickets', '0002_humanhandoff'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', 'updated_at'], name='agent_run_status_updated_idx'),
        ),
    ]
