# Generated by Django 5.2.17 on 2026-08-27 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('notification', 'Notification'), ('webhook', 'Webhook')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('retry_scheduled', 'Retry scheduled'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead', 'Dead')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField()),
                ('next_attempt_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('claim_token', models.UUIDField()),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('safe_error_code', models.CharField(blank=True, max_length=64)),
                ('retryable', models.BooleanField(blank=True, null=True)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notifications.delivery')),
            ],
            options={
                'ordering': ['delivery', 'attempt_number'],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='delivery_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['lease_expires_at'], name='delivery_lease_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['workspace', 'created_at'], name='delivery_ws_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='delivery_attempt_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gt', 0)), name='delivery_max_attempts_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='delivery_attempt_count_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'claimed'), ('claimed_at__isnull', False), ('lease_expires_at__isnull', False), ('claim_token__isnull', False)), models.Q(models.Q(('status', 'claimed'), _negated=True), ('claimed_at__isnull', True), ('lease_expires_at__isnull', True), ('claim_token__isnull', True)), _connector='OR'), name='delivery_claim_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('delivery', 'attempt_number'), name='delivery_attempt_number_uniq'),
        ),
    ]
