# Generated by Django 5.2.17 on 2026-08-27 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tools', '0003_alter_toolexecution_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medium', models.CharField(choices=[('email', 'Email')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('idempotency_key', models.CharField(max_length=200)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_delivery', to='notifications.delivery')),
                ('source_tool_execution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='notification_delivery', to='tools.toolexecution')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('recipient_email', ''), _negated=True), name='notification_delivery_recipient_not_blank'), models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='notification_delivery_idempotency_key_not_blank')],
            },
        ),
    ]
