# Generated by Django 5.2.17 on 2026-08-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationdelivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In progress"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("abandoned", "Abandoned"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
