# Generated by Django 5.2.17 on 2026-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_deliveryattempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='channel',
            field=models.CharField(choices=[('notification', 'Notification'), ('webhook', 'Webhook'), ('channel_response', 'Channel response')], max_length=20),
        ),
    ]
