# Generated by Django 5.2.17 on 2026-08-18 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
        ("customers", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="conversations.conversation",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_membership",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for human_agent messages; null for customer/system/ai_agent messages.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to="workspaces.workspacemembership",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["workspace", "status"], name="conv_ws_status_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["workspace", "customer"], name="conv_ws_customer_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["workspace", "assigned_to"], name="conv_ws_assignee_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["workspace", "-last_message_at"], name="conv_ws_lastmsg_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", False)),
                fields=("workspace", "external_id"),
                name="uniq_conversation_workspace_external_id",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "created_at"], name="msg_conv_created_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["workspace", "created_at"], name="msg_ws_created_idx"),
        ),
    ]
