# Generated by Django 5.2.17 on 2026-09-04 10:42
#
# Phase 16 Part F (section 33): adds a strictly-increasing, DB-assigned
# insertion sequence to Message, used as a deterministic ordering
# tie-breaker in place of the random UUID primary key. See
# Message.sequence's docstring in conversations/models.py for the full
# rationale (a created_at timestamp tie previously sorted by random id,
# which could silently invert the "newest history is retained" guarantee
# agents.context.build_conversation_context depends on).
#
# The backing PostgreSQL sequence is created explicitly (rather than
# relying on Django's own AutoField, which requires primary_key=True) so
# the ``sequence`` column gets its value from the database itself on every
# INSERT, never from application code — the same guarantee a plain
# BIGSERIAL column would give, expressed here as an ordinary sequence plus
# a ``db_default`` so Django's own migration state/model class stays a
# normal, explicit field.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SEQUENCE conversations_message_sequence_seq;",
            reverse_sql="DROP SEQUENCE IF EXISTS conversations_message_sequence_seq;",
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at", "sequence"]},
        ),
        migrations.AddField(
            model_name="message",
            name="sequence",
            field=models.BigIntegerField(
                db_default=models.Func(
                    models.Value("conversations_message_sequence_seq"), function="nextval"
                ),
                editable=False,
                unique=True,
            ),
        ),
        # Tie the sequence's lifecycle to the column it now backs — dropping
        # the column (a migration rollback) automatically drops the
        # sequence too, exactly like a real BIGSERIAL column would.
        migrations.RunSQL(
            sql=(
                "ALTER SEQUENCE conversations_message_sequence_seq "
                "OWNED BY conversations_message.sequence;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
