/**
 * Shared core used by both scripts/generate-api-types.mjs (writes the real
 * committed files) and scripts/check-api-types.mjs (writes to a throwaway
 * location and diffs) — one implementation of "how do we ask the backend
 * for its schema and turn that into TypeScript", so the two commands can
 * never drift from each other.
 */
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import path from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

export function resolveRoots(scriptsLibDir) {
  const frontendRoot = path.dirname(path.dirname(scriptsLibDir));
  const repoRoot = path.dirname(frontendRoot);
  const backendRoot = path.join(repoRoot, "backend");
  return { frontendRoot, repoRoot, backendRoot };
}

export function resolvePythonBin(backendRoot) {
  return process.platform === "win32"
    ? path.join(backendRoot, "venv", "Scripts", "python.exe")
    : path.join(backendRoot, "venv", "bin", "python");
}

/**
 * Generate the OpenAPI schema (YAML) and TypeScript types, writing them to
 * `schemaOutPath` / `typesOutPath`. Throws on failure. Requires no running
 * server/database/Redis — the schema is built by importing the Django app
 * config directly.
 */
export async function generateSchemaAndTypes({ backendRoot, schemaOutPath, typesOutPath, cwd }) {
  const pythonBin = resolvePythonBin(backendRoot);
  if (!existsSync(pythonBin)) {
    throw new Error(
      `Backend virtualenv not found at ${pythonBin}.\n` +
        "Create it first (see the repository root README's Quick Start) before regenerating API types.",
    );
  }

  const tmpDb = path.join(backendRoot, "schema_generation.sqlite3");
  const schemaEnv = {
    ...process.env,
    DEBUG: process.env.DEBUG ?? "True",
    SECRET_KEY: process.env.SECRET_KEY ?? "schema-generation-only",
    ALLOWED_HOSTS: process.env.ALLOWED_HOSTS ?? "localhost,127.0.0.1",
    DATABASE_URL: process.env.DATABASE_URL ?? `sqlite:///${tmpDb}`,
    REDIS_URL: process.env.REDIS_URL ?? "redis://localhost:6379/0",
  };

  const schemaResult = spawnSync(
    pythonBin,
    ["manage.py", "spectacular", "--file", schemaOutPath, "--fail-on-warn"],
    { cwd: backendRoot, env: schemaEnv, stdio: "inherit" },
  );

  if (existsSync(tmpDb)) {
    rmSync(tmpDb, { force: true });
  }

  if (schemaResult.status !== 0) {
    throw new Error("OpenAPI schema generation failed (see drf-spectacular output above).");
  }

  const schemaText = readFileSync(schemaOutPath, "utf-8");
  const ast = await openapiTS(schemaText, { cwd });
  const header =
    "/**\n" +
    " * This file was auto-generated by openapi-typescript.\n" +
    " * Do not make direct changes to the file.\n" +
    " */\n\n";
  writeFileSync(typesOutPath, header + astToString(ast));
}
