# Generated by Django 5.2.17 on 2026-08-19 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approvals", "0001_initial"),
        ("policies", "0001_initial"),
        ("tools", "0002_seed_demo_tool_definitions"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="policy_evaluation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_request",
                to="policies.policyevaluation",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_requests_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="risk_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_requests",
                to="policies.riskassessment",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="tool_execution",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_request",
                to="tools.toolexecution",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="approvaldecision",
            name="approval_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision",
                to="approvals.approvalrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["workspace", "status", "created_at"], name="approval_ws_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["workspace", "expires_at"], name="approval_ws_expires_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["required_role", "status"], name="approval_role_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="approval_expires_after_created",
            ),
        ),
    ]
