# Generated by Django 5.2.17 on 2026-08-20 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentrun_output_message_agentrun_trigger_message'),
        ('conversations', '0002_initial'),
        ('tickets', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('reason_code', models.CharField(choices=[('customer_requested', 'Customer requested a human'), ('unsupported_action', 'Unsupported action'), ('runtime_failure', 'Repeated bounded runtime failure'), ('low_confidence', 'Low-confidence retrieval/response'), ('policy_escalation', 'Business workflow requires an operator')], max_length=32)),
                ('safe_summary', models.CharField(max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_handoffs', to='agents.agentrun')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_handoffs', to='workspaces.workspacemembership')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_handoffs', to='conversations.conversation')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_handoffs', to='tickets.ticket')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_handoffs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status', '-created_at'], name='handoff_ws_status_idx'), models.Index(fields=['conversation', 'status'], name='handoff_conv_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'assigned'))), fields=('conversation',), name='handoff_one_active_per_conversation')],
            },
        ),
    ]
