# Generated by Django 5.2.17 on 2026-08-31 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0006_alter_agentrun_trigger'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=128)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('input_message', models.TextField()),
                ('seeded_context', models.JSONField(blank=True, default=dict)),
                ('expectations', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_cases_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dataset_id', 'key'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCaseSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('case_key', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=200)),
                ('input_message', models.TextField()),
                ('seeded_context', models.JSONField(blank=True, default=dict)),
                ('expectations', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='evaluations.evaluationcase')),
            ],
            options={
                'ordering': ['run_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_datasets_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_datasets', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='evaluationcase',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='evaluations.evaluationdataset'),
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider_mode', models.CharField(choices=[('deterministic', 'Deterministic (offline)')], default='deterministic', max_length=20)),
                ('threshold_config', models.JSONField(blank=True, default=dict)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('completed_cases', models.PositiveIntegerField(default=0)),
                ('passed_cases', models.PositiveIntegerField(default=0)),
                ('failed_cases', models.PositiveIntegerField(default=0)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('agent_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_runs', to='agents.agentversion')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_runs_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='evaluations.evaluationdataset')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scorer_output', models.JSONField(blank=True, default=dict)),
                ('passed', models.BooleanField(null=True)),
                ('failure_code', models.CharField(blank=True, choices=[('invalid_case', 'Invalid case'), ('agent_execution_failed', 'Agent execution failed'), ('budget_exceeded', 'Budget exceeded'), ('provider_failure', 'Provider failure'), ('forbidden_tool_violation', 'Forbidden tool violation'), ('policy_violation', 'Policy violation'), ('approval_violation', 'Approval violation'), ('outcome_mismatch', 'Outcome mismatch'), ('scoring_failed', 'Scoring failed'), ('cancelled', 'Cancelled')], max_length=32)),
                ('failure_message_safe', models.CharField(blank=True, max_length=500)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_results', to='agents.agentrun')),
                ('case_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='evaluations.evaluationcasesnapshot')),
                ('replay_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replays', to='evaluations.evaluationresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='evaluations.evaluationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='evaluationcasesnapshot',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_snapshots', to='evaluations.evaluationrun'),
        ),
        migrations.AddIndex(
            model_name='evaluationdataset',
            index=models.Index(fields=['workspace', 'status'], name='eval_dataset_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationdataset',
            index=models.Index(fields=['workspace', '-created_at'], name='eval_dataset_ws_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationdataset',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='eval_dataset_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='evaluationdataset',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='eval_dataset_workspace_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='evaluationcase',
            index=models.Index(fields=['dataset', 'status'], name='eval_case_dataset_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcase',
            constraint=models.UniqueConstraint(fields=('dataset', 'key'), name='eval_case_dataset_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['workspace', 'status'], name='eval_run_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['workspace', '-created_at'], name='eval_run_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['dataset', '-created_at'], name='eval_run_dataset_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(('completed_cases__lte', models.F('total_cases'))), name='eval_run_completed_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(('passed_cases__lte', models.F('completed_cases'))), name='eval_run_passed_lte_completed'),
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['run', 'status'], name='eval_result_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['run', 'passed'], name='eval_result_run_passed_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcasesnapshot',
            index=models.Index(fields=['run'], name='eval_case_snap_run_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcasesnapshot',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='eval_case_snap_run_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcasesnapshot',
            constraint=models.UniqueConstraint(fields=('run', 'case_key'), name='eval_case_snap_run_case_key_uniq'),
        ),
    ]
