# Generated by Django 5.2.17 on 2026-08-31 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_agentrun_trigger'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationresult',
            name='case_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='evaluations.evaluationcasesnapshot'),
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['case_snapshot'], name='eval_result_case_snap_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationresult',
            constraint=models.UniqueConstraint(condition=models.Q(('replay_of__isnull', True)), fields=('case_snapshot',), name='eval_result_one_initial_per_snapshot'),
        ),
    ]
