# Generated by Django 5.2.17 on 2026-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_evaluationresult_case_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationresult',
            name='failure_code',
            field=models.CharField(blank=True, choices=[('invalid_case', 'Invalid case'), ('agent_execution_failed', 'Agent execution failed'), ('budget_exceeded', 'Budget exceeded'), ('provider_failure', 'Provider failure'), ('forbidden_tool_violation', 'Forbidden tool violation'), ('policy_violation', 'Policy violation'), ('approval_violation', 'Approval violation'), ('outcome_mismatch', 'Outcome mismatch'), ('scoring_failed', 'Scoring failed'), ('cancelled', 'Cancelled'), ('worker_crash_recovered', 'Worker crash recovered')], max_length=32),
        ),
    ]
