# Generated by Django 5.2.17 on 2026-08-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='know_source_name_not_blank'),
        ),
    ]
