# Generated by Django 5.2.17 on 2026-08-19 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("google_calendar", "Google Calendar"),
                            ("email", "Email notifications"),
                            ("demo_commerce", "Demo commerce (orders & shipments)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("invalid_credentials", "Invalid credentials"),
                            ("degraded", "Degraded"),
                        ],
                        default="disabled",
                        max_length=20,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[("test", "Test / sandbox"), ("live", "Live / production")],
                        default="test",
                        max_length=8,
                    ),
                ),
                ("encrypted_credentials", models.TextField(blank=True)),
                ("credential_version", models.PositiveIntegerField(default=0)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_integration_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_connections",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["workspace", "status"], name="integ_conn_ws_status_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "provider"), name="uniq_integration_conn_ws_provider"
                    )
                ],
            },
        ),
    ]
