# Generated by Django 5.2.17 on 2026-08-19 03:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0002_agentrun_tool_call_count_agentversion_max_tool_calls_and_more"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=128, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("read_only", "Read only"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "side_effect_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("read", "Read"),
                            ("internal_write", "Internal write"),
                            ("external_write", "External write"),
                            ("financial", "Financial"),
                            ("destructive", "Destructive"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("handler_key", models.CharField(max_length=128)),
                ("default_timeout_seconds", models.PositiveIntegerField(default=5)),
                ("max_timeout_seconds", models.PositiveIntegerField(default=10)),
                ("max_retries", models.PositiveIntegerField(default=0)),
                (
                    "idempotency_mode",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("safe", "Safe to retry/replay"),
                            ("required", "Requires a caller-supplied key"),
                        ],
                        default="safe",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("key", ""), _negated=True),
                        name="tool_def_key_not_blank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_timeout_seconds__gt", 0), ("max_timeout_seconds__gt", 0)
                        ),
                        name="tool_def_timeouts_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ToolBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                (
                    "agent_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_bindings",
                        to="agents.agentversion",
                    ),
                ),
                (
                    "tool_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bindings",
                        to="tools.tooldefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("timed_out", "Timed out"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(blank=True, max_length=200)),
                ("arguments_fingerprint", models.CharField(blank=True, max_length=64)),
                ("arguments_redacted", models.JSONField(blank=True, default=dict)),
                ("result_redacted", models.JSONField(blank=True, default=dict)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("timeout_seconds", models.PositiveIntegerField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message_safe", models.CharField(blank=True, max_length=500)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_executions",
                        to="agents.agentrun",
                    ),
                ),
                (
                    "agent_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_executions",
                        to="agents.agentversion",
                    ),
                ),
                (
                    "tool_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="tools.toolbinding",
                    ),
                ),
                (
                    "tool_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="tools.tooldefinition",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_executions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="toolbinding",
            index=models.Index(
                fields=["agent_version", "enabled"], name="tool_binding_ver_enabled_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="toolbinding",
            constraint=models.UniqueConstraint(
                fields=("agent_version", "tool_definition"), name="tool_binding_version_tool_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="toolexecution",
            index=models.Index(
                fields=["workspace", "-created_at"], name="tool_exec_ws_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolexecution",
            index=models.Index(fields=["workspace", "status"], name="tool_exec_ws_status_idx"),
        ),
        migrations.AddIndex(
            model_name="toolexecution",
            index=models.Index(
                fields=["agent_run", "-created_at"], name="tool_exec_run_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolexecution",
            index=models.Index(
                fields=["tool_definition", "-created_at"], name="tool_exec_tool_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="toolexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__gte", 0)), name="tool_exec_attempt_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="toolexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("timeout_seconds__gt", 0)), name="tool_exec_timeout_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="toolexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("workspace", "tool_definition", "idempotency_key"),
                name="tool_exec_idempotency_uniq",
            ),
        ),
    ]
