# Generated by Django 5.2.17 on 2026-08-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_seed_demo_tool_definitions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("timed_out", "Timed out"),
                    ("cancelled", "Cancelled"),
                    ("waiting_for_approval", "Waiting for approval"),
                    ("blocked_by_policy", "Blocked by policy"),
                    ("approval_terminated", "Approval terminated"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
