# Generated by Django 5.2.17 on 2026-08-18 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("display_name", models.CharField(blank=True, max_length=300)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=32, null=True)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["workspace", "is_active"], name="cust_ws_active_idx"),
                    models.Index(fields=["workspace", "created_at"], name="cust_ws_created_idx"),
                    models.Index(fields=["workspace", "email"], name="cust_ws_email_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id__isnull", False)),
                        fields=("workspace", "external_id"),
                        name="uniq_customer_workspace_external_id",
                    )
                ],
            },
        ),
    ]
