# Generated by Django 5.2.17 on 2026-09-01 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0006_alter_agentrun_trigger'),
        ('conversations', '0002_initial'),
        ('customers', '0001_initial'),
        ('integrations', '0002_seed_integration_tool_definitions'),
        ('notifications', '0004_alter_delivery_channel'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('web_chat', 'Web chat'), ('email', 'Email'), ('generic_webhook', 'Generic signed webhook')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('unknown_customer_policy', models.CharField(choices=[('create', 'Create a new customer record'), ('reject', 'Reject the event')], default='create', max_length=16)),
                ('encrypted_signing_secret', models.TextField(blank=True)),
                ('secret_created_at', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('agent_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_endpoints', to='agents.agentversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channel_endpoints', to=settings.AUTH_USER_MODEL)),
                ('integration_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_endpoints', to='integrations.integrationconnection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_endpoints', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelResponseDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_address', models.CharField(max_length=320)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('thread_reference', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_response_delivery', to='notifications.delivery')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_deliveries', to='channel_ingress.channelendpoint')),
                ('source_message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='channel_response_delivery', to='conversations.message')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_session', to='conversations.conversation')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='customers.customer')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='channel_ingress.channelendpoint')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundChannelEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('provider_thread_id', models.CharField(blank=True, max_length=255)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('payload_digest', models.CharField(max_length=64)),
                ('external_identity', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=16)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_channel_events', to='conversations.conversation')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_events', to='channel_ingress.channelendpoint')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_channel_event', to='conversations.message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_channel_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='channelendpoint',
            index=models.Index(fields=['workspace', 'status'], name='chan_ep_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='channelendpoint',
            index=models.Index(fields=['workspace', 'channel'], name='chan_ep_ws_channel_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='channel_endpoint_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='channelresponsedelivery',
            constraint=models.CheckConstraint(condition=models.Q(('destination_address', ''), _negated=True), name='channel_response_delivery_destination_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='channelresponsedelivery',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='channel_response_delivery_idempotency_key_not_blank'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['workspace', '-created_at'], name='chat_sess_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundchannelevent',
            index=models.Index(fields=['workspace', '-created_at'], name='chan_evt_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundchannelevent',
            index=models.Index(fields=['endpoint', 'provider_thread_id'], name='chan_evt_ep_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundchannelevent',
            index=models.Index(fields=['status', 'received_at'], name='chan_evt_status_recv_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundchannelevent',
            constraint=models.UniqueConstraint(fields=('endpoint', 'provider_event_id'), name='uniq_inbound_event_endpoint_provider_event_id'),
        ),
    ]
