# Generated by Django 5.2.17 on 2026-08-19 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tools", "0002_seed_demo_tool_definitions"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policy_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("priority", models.PositiveIntegerField()),
                ("enabled", models.BooleanField(default=True)),
                ("tool_key", models.CharField(blank=True, max_length=128)),
                ("risk_levels", models.JSONField(blank=True, default=list)),
                ("side_effect_types", models.JSONField(blank=True, default=list)),
                ("condition_config", models.JSONField(blank=True, default=dict)),
                (
                    "effect",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("deny", "Deny"),
                            ("require_approval", "Require approval"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required_role", models.CharField(blank=True, max_length=32)),
                ("approval_ttl_seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="policies.policyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tool_key", models.CharField(max_length=128)),
                (
                    "base_risk",
                    models.CharField(
                        choices=[
                            ("read_only", "Read only"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "effective_risk",
                    models.CharField(
                        choices=[
                            ("read_only", "Read only"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "side_effect_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("read", "Read"),
                            ("internal_write", "Internal write"),
                            ("external_write", "External write"),
                            ("financial", "Financial"),
                            ("destructive", "Destructive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("factors", models.JSONField(blank=True, default=dict)),
                (
                    "tool_execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessment",
                        to="tools.toolexecution",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessments",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("deny", "Deny"),
                            ("require_approval", "Require approval"),
                        ],
                        max_length=20,
                    ),
                ),
                ("decision_code", models.CharField(max_length=64)),
                ("safe_reason", models.CharField(max_length=500)),
                ("matched_rule_ids", models.JSONField(blank=True, default=list)),
                (
                    "tool_execution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_evaluation",
                        to="tools.toolexecution",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_evaluations",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluations",
                        to="policies.policyversion",
                    ),
                ),
                (
                    "risk_assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_evaluation",
                        to="policies.riskassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(fields=["workspace", "status"], name="policy_ws_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="policy",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True), name="policy_name_not_blank"
            ),
        ),
        migrations.AddConstraint(
            model_name="policy",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"), name="policy_workspace_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="policy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("workspace",),
                name="policy_one_active_per_workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="policyversion",
            index=models.Index(fields=["policy", "status"], name="policy_ver_policy_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.UniqueConstraint(
                fields=("policy", "version"), name="policy_version_policy_version_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("policy",),
                name="policy_version_one_active_per_policy",
            ),
        ),
        migrations.AddIndex(
            model_name="policyrule",
            index=models.Index(
                fields=["policy_version", "enabled"], name="policy_rule_ver_enabled_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True), name="policy_rule_name_not_blank"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyrule",
            constraint=models.UniqueConstraint(
                fields=("policy_version", "priority"), name="policy_rule_version_priority_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyrule",
            constraint=models.UniqueConstraint(
                fields=("policy_version", "name"), name="policy_rule_version_name_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="riskassessment",
            index=models.Index(fields=["workspace", "-created_at"], name="risk_ws_created_idx"),
        ),
        migrations.AddIndex(
            model_name="policyevaluation",
            index=models.Index(
                fields=["workspace", "-created_at"], name="policy_eval_ws_created_idx"
            ),
        ),
    ]
