# Generated by Django 5.2.17 on 2026-08-27 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0002_notificationdelivery'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=2048)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('subscribed_event_types', models.JSONField(blank=True, default=list)),
                ('encrypted_signing_secret', models.TextField(blank=True)),
                ('secret_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_endpoints_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('approval.requested', 'Approval requested'), ('approval.approved', 'Approval approved'), ('approval.rejected', 'Approval rejected'), ('approval.expired', 'Approval expired'), ('handoff.created', 'Human handoff created')], max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_delivery', to='notifications.delivery')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='workspaces.workspace')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='webhooks.webhookendpoint')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='webhooks.webhookevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['workspace', 'status'], name='webhook_ep_ws_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='webhook_endpoint_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('url', ''), _negated=True), name='webhook_endpoint_url_not_blank'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['workspace', '-created_at'], name='webhook_evt_ws_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='webhook_event_version_gt_0'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['workspace', '-created_at'], name='webhook_dlv_ws_created_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', '-created_at'], name='webhook_dlv_ep_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('endpoint', 'event'), name='webhook_delivery_endpoint_event_uniq'),
        ),
    ]
