# Generated by Django 5.2.17 on 2026-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('workspace.created', 'Workspace created'), ('workspace.updated', 'Workspace updated'), ('workspace.member_added', 'Member added'), ('workspace.member_role_changed', 'Member role changed'), ('workspace.member_removed', 'Member removed'), ('workspace.ownership_transferred', 'Ownership transferred'), ('customer.deactivated', 'Customer deactivated'), ('conversation.assigned', 'Conversation assigned'), ('conversation.reassigned', 'Conversation reassigned'), ('conversation.closed', 'Conversation closed'), ('conversation.reopened', 'Conversation reopened'), ('ticket.assigned', 'Ticket assigned'), ('ticket.reassigned', 'Ticket reassigned'), ('ticket.status_changed', 'Ticket status changed'), ('ticket.resolved', 'Ticket resolved'), ('ticket.reopened', 'Ticket reopened'), ('knowledge.source_created', 'Knowledge source created'), ('knowledge.source_updated', 'Knowledge source updated'), ('knowledge.source_deactivated', 'Knowledge source deactivated'), ('knowledge.document_uploaded', 'Knowledge document uploaded'), ('knowledge.document_retry_requested', 'Knowledge document retry requested')], max_length=64),
        ),
    ]
