# Generated by Django 5.2.17 on 2026-08-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("workspace.created", "Workspace created"),
                    ("workspace.updated", "Workspace updated"),
                    ("workspace.member_added", "Member added"),
                    ("workspace.member_role_changed", "Member role changed"),
                    ("workspace.member_removed", "Member removed"),
                    ("workspace.ownership_transferred", "Ownership transferred"),
                    ("customer.deactivated", "Customer deactivated"),
                    ("conversation.assigned", "Conversation assigned"),
                    ("conversation.reassigned", "Conversation reassigned"),
                    ("conversation.closed", "Conversation closed"),
                    ("conversation.reopened", "Conversation reopened"),
                    ("ticket.assigned", "Ticket assigned"),
                    ("ticket.reassigned", "Ticket reassigned"),
                    ("ticket.status_changed", "Ticket status changed"),
                    ("ticket.resolved", "Ticket resolved"),
                    ("ticket.reopened", "Ticket reopened"),
                    ("knowledge.source_created", "Knowledge source created"),
                    ("knowledge.source_updated", "Knowledge source updated"),
                    ("knowledge.source_deactivated", "Knowledge source deactivated"),
                    ("knowledge.document_uploaded", "Knowledge document uploaded"),
                    ("knowledge.document_retry_requested", "Knowledge document retry requested"),
                    ("agent.definition_created", "Agent definition created"),
                    ("agent.definition_updated", "Agent definition updated"),
                    ("agent.version_created", "Agent version created"),
                    ("agent.version_published", "Agent version published"),
                    ("agent.run_started", "Agent run started"),
                    ("agent.run_cancelled", "Agent run cancelled"),
                    ("agent.run_failed", "Agent run failed"),
                    ("agent.run_completed", "Agent run completed"),
                    ("tool.binding_created", "Tool binding created"),
                    ("tool.binding_updated", "Tool binding updated"),
                    ("tool.binding_disabled", "Tool binding disabled"),
                    ("integration.connection_created", "Integration connection created"),
                    ("integration.connection_updated", "Integration connection updated"),
                    ("integration.credentials_rotated", "Integration credentials rotated"),
                    ("integration.connection_disabled", "Integration connection disabled"),
                    ("integration.connection_enabled", "Integration connection enabled"),
                    ("integration.connection_tested", "Integration connection tested"),
                    ("payment.refund_executed", "Payment refund executed"),
                ],
                max_length=64,
            ),
        ),
    ]
